name: CI

on:
  push:
    branches: [ master ]
    tags:     [ "v*" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -cover -covermode=atomic -coverprofile=coverage.out -v ./...
      
    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
        fail_ci_if_error: true
        verbose: true
        
    - name: Remove coverage file
      run: rm ./coverage.out

    - name: Verify Modules
      run: |
        go mod tidy
        go mod verify

    - name: Ensure no files modified
      run: >
        if [ `git status -s | wc -l` -gt 0 ]; then
          echo "Expected no new/modified files."
          echo "Got (git status -s):"
          git status -s
          echo ""
          echo "Diff"
          git --no-pager diff
          exit 1
        fi

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
